# deployment openldap server

registry_name: "quay.io"
registry_org: "dnessill"
openldap_image_tag: "latest"
openldap_image_name: "my-openldap"
#openldap_namespace_name: "openldap"
openldap_namespace_name: "openldap"


# deployment phpldapadmin

phpldapadmin_image_tag: "latest"
phpldapadmin_image_name: "phpldapadmin"
#phpldapadmin_namespace_name: "phpldapadmin"
phpldapadmin_namespace_name: "openldap"

# ldap group sync
#ldap_sync_namespace_name: "ldap-sync"
ldap_sync_namespace_name: "openldap"
