apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oc-cli
rules:
  - apiGroups:
      - ''
      - user.openshift.io
      - v1
      - config.openshift.io
    resources:
      - configmaps
      - secrets
      - groups
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
