apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-3
  namespace: {{ .Values.namespace_name }}
data:
  pod3: |
    <html>
    <h1>Welcome</h1>
    <h1>Hi! This is HTTP Server 3 </h1>
    </html>
