apiVersion: v1
kind: Service
metadata:
  name: ccam-authorization-manager-gateway
  namespace: {{ .Values.namespace_name }}
spec:
  internalTrafficPolicy: Cluster
  selector:
    app: ccam-authorization-manager-gateway
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
