apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: {{ .Values.namespace_name }}
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  http:
  - route:
    - destination:
        host: nginx-http-1
  tcp:
  - route:
    - destination:
        host: nginx-http-1
        port:
          number: 80
