apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: {{ .Values.namespace_name }}
spec:
  hosts:
  - "nginx-http-ossm-tls-multiple-endpoints.apps.sharedocp416.sbr-shift.gsslab.brq2.redhat.com"
  gateways:
  - istio-system/nginx-gateway
  http:
  - headers:
        request:
          remove:
            - x-forwarded-client-cert
        response:
          remove:
            - x-envoy-peer-metadata
            - x-envoy-peer-metadata-id
            - x-forwarded-client-cert
            - x-forwarded-for
            - x-forwarded-proto
            - x-envoy-attempt-count
            - x-envoy-internal
            - x-envoy-upstream-service-time
    match:
    - uri:
        prefix: /v1/k2view/api/searchCustomer
    route:
    - destination:
        host: nginx-http-1
        port:
          number: 80
  - headers:
        request:
          remove:
            - x-forwarded-client-cert
        response:
          remove:
            - x-envoy-peer-metadata
            - x-envoy-peer-metadata-id
            - x-forwarded-client-cert
            - x-forwarded-for
            - x-forwarded-proto
            - x-envoy-attempt-count
            - x-envoy-internal
            - x-envoy-upstream-service-time
    match:
    - uri:
        prefix: /v1/k2view/api/GetOutage
    route:
    - destination:
        host: nginx-http-1
        port:
          number: 80
