apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ingress-routing
  namespace: app-ccam-rosa-acc
spec:
  gateways:
  - istio-system/app-ccam-rosa-acc-ingress
  hosts:
  - app-ccam-rosa.acc.microbots.apps.sharedocp416.sbr-shift.gsslab.brq2.redhat.com 
  http:
  - headers:
      request:
        remove:
        - x-forwarded-client-cert
      response:
        remove:
        - x-envoy-peer-metadata
        - x-envoy-peer-metadata-id
        - x-forwarded-client-cert
        - x-forwarded-for
        - x-forwarded-proto
        - x-envoy-attempt-count
        - x-envoy-internal
        - x-envoy-upstream-service-time
    match:
    - uri:
        prefix: /v1/k2view/api/getOutageTickets
    route:
    - destination:
        host: ccam-authorization-manager-gateway
        port:
          number: 80
