apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: {{ .Values.namespace_name }}
spec:
  hosts:
  - "nginx-http-ossm-tls-multiple-endpoints.apps.sharedocp416.sbr-shift.gsslab.brq2.redhat.com"
  gateways:
  - nginx-gateway
  http:
  - match:
    - uri:
        prefix: /v1/k2view/api/searchCustomer
    route:
    - destination:
        host: nginx-http-1
        port:
          number: 80
  - match:
    - uri:
        exact: /nginx-2
    route:
    - destination:
        host: nginx-http-2
        port:
          number: 80
