apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openldap
    app.kubernetes.io/component: openldap
    app.kubernetes.io/instance: openldap
  name: openldap
  namespace: {{ .Values.openldap_namespace_name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: openldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: openldap
    spec:
      containers:
      - env:
        - name: LDAP_ADMIN_PASSWORD
          value: anypassword
        image: {{ .Values.registry_name }}/{{ .Values.registry_org }}/{{ .Values.opendap_image_name }}:{{ .Values.image_tag }}
        imagePullPolicy: Always
        name: openldap
        ports:
        - containerPort: 636
          protocol: TCP
        - containerPort: 389
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: openldap
      serviceAccountName: openldap
      terminationGracePeriodSeconds: 30
