kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openldap
  namespace: {{ .Values.openldap_namespace_name }}
subjects:
  - kind: ServiceAccount
    name: openldap
    namespace: {{ .Values.openldap_namespace_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid   
