apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpldapadmin
    app.kubernetes.io/component: phpldapadmin
    app.kubernetes.io/instance: phpldapadmin
  name: phpldapadmin
  namespace: {{ .Values.phpldapadmin_namespace_name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: phpldapadmin
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: phpldapadmin
    spec:
      containers:
      - env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: openldap.{{ .Values.openldap_namespace_name }}.svc.cluster.local
        image: {{ .Values.registry_name }}/{{ .Values.registry_org }}/{{ .Values.phpldapadmin_image_name }}:{{ .Values.phpldapadmin_image_tag }}
        imagePullPolicy: IfNotPresent
        name: phpldapadmin
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: phpldapadmin
      serviceAccountName: phpldapadmin
      securityContext: {}
      terminationGracePeriodSeconds: 30
