apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
    app.kubernetes.io/component: phpldapadmin
    app.kubernetes.io/instance: phpldapadmin
  name: phpldapadmin
  namespace: {{ .Values.openldap_namespace_name }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp
    port: 8181
    protocol: TCP
    targetPort: 80
  selector:
    deployment: phpldapadmin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
