apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx-http-ossm-tls-multiple-endpoints
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: This is just an example.
  destinations:
    - name: in-cluster
      namespace: nginx-http-ossm-tls-multiple-endpoints
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/dnessill/reproductions'
status: {}
