apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claim_name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.sc_name }}
  resources:
    requests:
      storage: 4Gi
