apiVersion: v1
kind: Service
metadata:
  name: nginx-http
  namespace: {{ .Values.namespace_name }}
spec:
  selector:
    app: nginx-http
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
      targetPort: 80
