apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: {{ .Values.namespace_name }}
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  http:
  - match:
    route:
    - destination:
        host: nginx-http
        port:
          number: 80
    - destination:
        host: nginx-http
        port:
          number: 80
  route:
  - destination:
      host: nginx-http
      subset: "v1"
    weight: 80
  - destination:
      host: nginx-http
      subset: "v2"
    weight: 20

