apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
    app.kubernetes.io/component: openldap
    app.kubernetes.io/instance: openldap
  name: openldap
  namespace: {{ .Values.openldap_namespace_name }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 389-tcp
    port: 389
    protocol: TCP
    targetPort: 389
  - name: 636-tcp
    port: 636
    protocol: TCP
    targetPort: 636
  selector:
    deployment: openldap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
