apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: phpldapadmin-application
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: phpldapadmin
  project: ldap-identity-provider
  source:
    helm:
      valueFiles:
        - values.yaml
    path: ldap-identity-provider/charts-phpldapadmin/
    repoURL: 'https://github.com/dnessill/reproductions'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
