apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2023-01-23T12:09:38Z"
  generation: 8
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: d5bbcb29-8d6f-4774-8a92-e2fca221ffbd
  resourceVersion: "29605200"
  uid: c0f1a379-cb52-4358-ac00-24ce630e5b1c
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - cn
      bindDN: cn=admin,dc=example,dc=com
      bindPassword:
        name: ldap-secret
      insecure: true
      url: ldap://openldap.ldapserver.svc.cluster.local/ou=users,dc=example,dc=com?cn
    mappingMethod: claim
    name: ldapidp
    type: LDAP
